create table trainee_trainer (
                                 trainee_id integer not null,
                                 trainer_id integer not null
);

create table trainees (
                          id integer generated by default as identity,
                          address varchar(255),
                          date_of_birth date,
                          user_id integer,
                          primary key (id)
);

create table trainers (
                          id integer generated by default as identity,
                          specialization_id integer,
                          user_id integer,
                          primary key (id)
);

create table training_types (
                                id integer generated by default as identity,
                                training_type_name varchar(255) not null,
                                primary key (id)
);

create table trainings (
                           id integer generated by default as identity,
                           duration numeric(19,2) not null,
                           training_date date not null,
                           training_name varchar(255) not null,
                           trainee_id integer,
                           trainer_id integer,
                           training_type_id integer,
                           primary key (id)
);

create table users (
                       id integer generated by default as identity,
                       first_name varchar(255) not null,
                       is_active boolean not null,
                       last_name varchar(255) not null,
                       password varchar(255) not null,
                       username varchar(255) not null,
                       primary key (id)
);

alter table if exists trainees
drop constraint if exists UK6yjkrphplllspvtco5gaax03b;

alter table if exists trainees
    add constraint UK6yjkrphplllspvtco5gaax03b unique (user_id);

alter table if exists trainers
drop constraint if exists UKse8qmhomor3guutjui5wfmrk3;

alter table if exists trainers
    add constraint UKse8qmhomor3guutjui5wfmrk3 unique (user_id);

alter table if exists users
drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;

alter table if exists users
    add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);

alter table if exists trainee_trainer
    add constraint FKsis342w57b177o84peanydlrp
    foreign key (trainer_id)
    references trainers;

alter table if exists trainee_trainer
    add constraint FK27f1le516f824l8owvnc4mvs1
    foreign key (trainee_id)
    references trainees;

alter table if exists trainees
    add constraint FKcy6e52861i61gaajadiq70lnt
    foreign key (user_id)
    references users;

alter table if exists trainers
    add constraint FK7cbp7k5ur2e10a5nj424nu1tv
    foreign key (specialization_id)
    references training_types;

alter table if exists trainers
    add constraint FKmkxcvfr0uu3pwv772aurye5w7
    foreign key (user_id)
    references users;

alter table if exists trainings
    add constraint FK4btmw0yu4tbogiw8qi0ewba74
    foreign key (trainee_id)
    references trainees;

alter table if exists trainings
    add constraint FKbqwj5wievnuonuxv60wg6rr48
    foreign key (trainer_id)
    references trainers;

alter table if exists trainings
    add constraint FKovn6ewpej7cxhjx55tovddhnj
    foreign key (training_type_id)
    references training_types;



